Sifchain/sifnode

ui/README.md
As we are now going open source this adds an under construction message to the frontend repo.
=> Add under construction message to frontend repo

ui/app/src/components/tokenSelector/SelectTokenDialog.vue, ui/app/src/components/tokenSelector/useSelectToken.ts, ui/app/src/views/AddLiquidityPage.vue, ui/app/src/views/CreatePairPage.vue, ui/app/src/views/SwapPage.vue
Disable previously selected items
=> Disable previously selected items

docs/adr-001-peggy-with-sifnode.md
It is the ADR to explain current solution - Peggy as module in Sifnode.
=> add adr related to peggy.

ui/app/src/components/currencyPairPanel/Index.vue, ui/app/src/components/currencyfield/CurrencyField.vue, ui/app/src/components/tokenSelector/SelectTokenDialog.vue, ui/app/src/views/AddLiquidityPage.vue, ui/app/src/views/CreatePairPage.vue, ui/app/src/views/SwapPage.vue
There was a strange bug in vue that appears to be resolved by avoiding hyphens in events. I suspect a framework bug.
=> Fix vue event issues by avoiding hyphens in events

api/openapi/peggy_get.yml, api/openapi/peggy_post.yml
Add swagger interface file for peggy related functions.
=> add peggy swagger file.

build/rakelib/chain.rake
Simple rake task to export state.
=> [ChainOps] Feature/export-state

.github/workflows/testnet.yml
Build ebrelayer and push to Docker Hub on merge into develop.
=> [ChainOps] feature/ebrelayer-build

build/rakelib/validator.rake, readme.md, tools/sifgen/common/types/genesis.go
=> [ChainOps] feature/sifgen-token-denom

testnet-contracts/package.json, testnet-contracts/truffle-config.js, testnet-contracts/yarn.lock
if the size of contract out of limit of EVM, the deployment will be failed. add the plugin to check after any update in contract.
=> add the plugin to show size of each contract.

build/rakelib/cluster.rake, build/rakelib/genesis.rake, build/rakelib/helpers.rake, build/scripts/entrypoint.sh, cmd/sifgen/main.go, tools/sifgen/network/network.go, tools/sifgen/network/types/config.go, tools/sifgen/node/node.go, tools/sifgen/sifgen.go, tools/sifgen/utils/cli.go
Ability to reset a node or the entire network.
=> [ChainOps] feature/node-reset

readme.md
Updated README for the updated testnet.
=> [ChainOps] feature/monkey-bars-testnet-4

ui/app/src/components/currencyPairPanel/Index.vue, ui/app/src/components/currencyfield/CurrencyField.vue, ui/app/src/components/wallet/useWalletButton.ts, ui/app/src/hooks/useCore.ts, ui/app/src/router/index.ts, ui/app/src/views/CreatePoolPage.vue, ui/app/src/views/PoolPage.vue, ui/app/src/views/SwapPage.vue, ui/core/src/actions/sifWalletActions.ts, ui/core/src/api/EthereumService/utils/getFakeTokens.ts, ui/core/src/api/EthereumService/utils/getWeb3Provider.ts, ui/core/src/api/MarketService/index.ts, ui/core/src/api/SifService/SifClient.ts, ui/core/src/api/SifService/index.ts, ui/core/src/api/SifService/x/clp/index.ts, ui/core/src/constants/tokens.ts, ui/core/src/hooks/poolCalculator.test.ts, ui/core/src/hooks/poolCalculator.ts
* Max button working on swap
* Fix cannot create ceth pool bug
* Made it so you cannot unselect rowan for liquidity pools
* Add liquidity will create a pool if it doesn't exist
=> Fix up addLiquidity vs createPool

cmd/ebrelayer/main.go, cmd/ebrelayer/relayer/ethereum.go, cmd/ebrelayer/txs/registry.go, cmd/ebrelayer/txs/relayToEthereum.go, cmd/ebrelayer/txs/signature.go
Relayer just print error and quit if any exceptional case before. Add better error handling for relayer.
=> Feature improve relayer error handling

.github/workflows/merged.yml
=> [ChainOps] hotfix/workflow-merge

cmd/ebrelayer/relayer/network_test.go
A wrong test case added, remove it via the pr.
=> remove a wrong test case.

.github/workflows/merged.yml
=> [ChainOps] hotfix/namespace-delete

.github/workflows/feature.yml
=> [ChainOps] feature/aws-cli-upgrade

deploy/scripts/entrypoint.sh
Changed gas from auto to 200000.
=> [ChainOps] hotfix/change-gas-amount

deploy/genesis/docker-compose.yml, deploy/scripts/entrypoint.sh
=> [ChainOps] feature/single-relayer

readme.md
Monkey Bars Testnet v5 update.
=> [ChainOps] feature/readme-update

.gitignore, deploy/rake/genesis.rake
=> [ChainOps] feature/tee

readme.md
Monkey Bars Testnet v6 README.
=> [ChainOps] feature/monkey-bars-v6

deploy/scripts/entrypoint.sh
=> [ChainOps] hotfix/more-gas

deploy/etc/supervisor/conf.d/supervisord.conf, deploy/genesis/docker-compose.yml, deploy/helm/sifnode/templates/sifnodecli-deployment.yaml, deploy/rake/genesis.rake
CORS support. Fixed a bug in the updated rake task. Docker compose cleanup.
=> [ChainOps] feature/cors

docs/clp-adr.md
First draft for the ADR . 
Looking for recommendations for things to include .
=> [Clp] Adr doc

.github/workflows/smart-contracts.yml, smart-contracts/README.md, smart-contracts/package-lock.json, smart-contracts/package.json
Setup the cicd for the smart contract tests.
=> [Peggy] cicd setting for smart contracts

cmd/ebrelayer/Dockerfile
=> [ChainOps] bugfix/relayer-build

deploy/rake/genesis.rake, test/integration/peggy-basic-test-docker.py, test/integration/peggy-e2e-test.py, test/integration/test_utilities.py
Fixes issue where integration tests fail because they don't wait long enough.
=> [Peggy] Better waiting for balances in integration tests

.github/workflows/go.yml, .github/workflows/node.yml
To verify if any backend changes break UI.
=> Always run UI tests for backend changes.

.github/ISSUE_TEMPLATE/feature_request.md
Simple feature request template.
=> Added feature request template

smart-contracts/.gitignore, smart-contracts/deployments/merry-go-round/.openzeppelin/ropsten.json, smart-contracts/deployments/merry-go-round/.openzeppelin/unknown-1337.json, smart-contracts/deployments/sandpit/.openzeppelin/ropsten.json, smart-contracts/deployments/sandpit/.openzeppelin/unknown-1337.json
=> [ChainOps] Missing contract folders.

x/clp/client/cli/query.go, x/clp/handler.go, x/clp/handler_test.go, x/clp/keeper/calculations.go, x/clp/keeper/querier.go, x/clp/keeper/querier_test.go, x/clp/types/types.go
=> added asset details to query liquidity provider response

.github/workflows/release.yml
=> [ChainOps] bugfix/tag-name

ui/chains/ethereum/package.json, ui/chains/ethereum/yarn.lock
Truffle missing when invoked for fresh install.
=> [Bug] ui/chains/ethereum: yarn add truffle (include for local development)

test/integration/assemble_data.sh, test/integration/docker-compose-integration.yml, test/integration/integration-entrypoint.sh, test/integration/no_whitelisted_validators.py, test/integration/peggy-e2e-test.py, test/integration/setup_sifchain.sh, test/integration/shell_utilities.sh, test/integration/sifchain_logs.sh, test/integration/start-integration-env.sh, test/integration/test_utilities.py, test/integration/vagrant/Makefile
Support for testing that no balance changes should happen if you don't whitelist validators
=> Add support for calling sifnoded add-genesis-validators to integration tests

deploy/rake/cluster.rake, deploy/rake/genesis.rake, deploy/rake/helpers.rake, tools/sifgen/common/types/config.go, tools/sifgen/node/node.go
CORS config for the RPC interface. 
Several rake task tweaks.
=> [ChainOps] CORS Support for the RPC interface.

deploy/helm/ebrelayer/templates/deployment.yaml, deploy/helm/ebrelayer/templates/secret.yaml, deploy/helm/ebrelayer/values.yaml, deploy/helm/sifnode/templates/sifnode-deployment.yaml, deploy/helm/sifnode/templates/sifnode-secret.yml, deploy/helm/sifnode/values.yaml, deploy/rake/cluster.rake
Don't store the mnemonic as a secret nor as an ENV var on the k8s pod.
=> [ChainOps] Remove Mnemonic from secrets/ENV.

deploy/helm/ethereum/templates/geth-deployment.yaml, deploy/helm/ethereum/values.yaml, deploy/rake/cluster.rake
General tweaks/updates to running a full ETH node on k8s.
=> [ChainOps] ETH Updates

docs/tutorials/k8s.md
Minor fix for the k8s tutorial document.
=> [ChainOps] Doc tweaks.

smart-contracts/Makefile, test/integration/Makefile, test/integration/assemble_data.sh, test/integration/execute_integration_tests_main.sh, test/integration/sifchain_logs.sh, test/integration/start-integration-env.sh, test/integration/vagrant/.gitignore, test/integration/vagrant/Makefile
A few improvements I made while looking at that javascript rounding issue
=> [Peggy] Minor integration test cleanup

readme.md
Added the block explorer URL to the README.
=> [ChainOps] README updates.

deploy/helm/sifnode/values.yaml, deploy/rake/cluster.rake, deploy/rake/validator.rake
Several items overlooked with the recent cosmovisor integration.
=> [ChainOps] Deployment bugfixes.

ui/package.json
This will update our local configuration after migration so our contract addresses are linked to deployed addresses
=> [Frontend] Automatically update testing contract addresses

cmd/sifnoded/genaccounts.go, cmd/sifnoded/main.go, x/ethbridge/alias.go, x/ethbridge/client/cli/tx.go, x/ethbridge/client/module_client.go, x/ethbridge/handler.go, x/ethbridge/keeper/keeper.go, x/ethbridge/types/codec.go, x/ethbridge/types/events.go, x/ethbridge/types/expected_keepers.go, x/ethbridge/types/msgs.go, x/oracle/alias.go, x/oracle/genesis.go, x/oracle/keeper/adminAccount.go, x/oracle/keeper/adminAccount_test.go, x/oracle/keeper/keeper.go, x/oracle/keeper/validatorWhiteList.go, x/oracle/types/errors.go, x/oracle/types/genesis.go, x/oracle/types/keys.go
We need an admin account with privilege to update validator whitelist at the runtime.
=> Feature add oracle admin

ui/core/src/api/EthereumService/EthereumService.test.ts
Suggestion for the fee-savings branch
=> Change test to just check that balance is a number

scripts/bugs/bug267.sh, scripts/init.sh, x/clp/client/cli/tx.go, x/clp/client/cli/tx_test.go, x/clp/handler.go, x/clp/keeper/executors.go, x/clp/types/errors.go
So after plugging in sensible numbers into CLP for the demo I realised something was different to the numbers we were getting on frontend. Reading through the handler for swap I noticed an error where we are finalizing the swap amount as the result of the first swap only and not a double swap which is required when swapping to tokens other than rowan. Surprised we missed this in test coverage.
=> [CLP] Error in swap routine

x/ethbridge/handler.go, x/ethbridge/types/msgs.go
There is typo for update whitelist message json.
=> fix a typo.

ui/chains/peggy/migrate.sh, ui/package.json, ui/yarn.lock
This fixes issue where the project would not build locally.
=> [ui] bug/dev-chain-migrate

cmd/sifgen/main.go
Set the IP Address for the peer node.
=> [ChainOps] Correctly set the peer IP address.

cmd/sifgen/main.go, deploy/helm/sifnode/values.yaml, deploy/rake/validator.rake
Revert back to a precision of 1e8.
=> [ChainOps] 1e8.

deploy/helm/sifnode/values.yaml, deploy/rake/genesis.rake, readme.md
=> [ChainOps] Merry-go-Round.

ui/app/src/components/poolList/SinglePool.vue, ui/app/src/hooks/useCore.ts
This shows how to expose the config to the frontend to use to assemble urls
=> Provide app config to UI

cmd/ebrelayer/main.go, deploy/helm/ebrelayer/templates/deployment.yaml, deploy/helm/ebrelayer/values.yaml, deploy/rake/cluster.rake
Relayer bugfixes around gas support.
=> [ChainOps] Relayer fixes.

app/app.go, deploy/helm/sifnode/templates/sifnode-deployment.yaml, deploy/helm/sifnode/values.yaml, tools/sifgen/genesis/genesis.go
=> [ChainOps] Voting tweaks.

ui/app/src/components/Notifications.vue, ui/app/src/views/CreatePoolPage.vue, ui/app/src/views/RemoveLiquidityPage.vue, ui/app/src/views/SwapPage.vue, ui/core/src/actions/clp/index.ts, ui/core/src/actions/peg/index.ts, ui/core/src/api/SifService/SifService.ts, ui/core/src/api/utils/Notifications.ts
This PR adds some basic error handling for clp and peggy. 
* Add try catch around service calls in usecases to handle errors and notifications
* FIxed a display error on the notification component were the bullet was getting squashed
_Noting a heap of linting noise occurring have updated this ticket to the backlog accordingly to fail tests on lint failure: https://app.asana.com/0/1199566806437637/1199668784029542_
=> [Frontend] Feature/error notifications

ui/core/src/assets.ethereum.ropsten.json, ui/core/src/config.sandpit.json
=> [ui] chore/config-update

cmd/ebrelayer/relayer/ethereum.go, cmd/ebrelayer/txs/relayToCosmos.go
roll back multiple message solution since some transaction error found.
=> roll back multiple message solution.

ui/app/src/views/PegAssetPage.vue
This fixes the inability of the UI to peg or unpeg the max amount.
=> [Frontend] Fix unpeg max not working

deploy/helm/sifnode/templates/sifnodecli-deployment.yaml
=> [ChainOps] LCD Init fixes.

ui/app/src/views/PegAssetPage.vue
This fixes https://app.asana.com/0/1199521986937893/1199875289046859 but it looks as if the backend needs this amount to be one wei less than balance
=> [Frontend] Remove rounding on balance checking in peg/unpeg

ui/core/src/actions/clp/index.ts, ui/core/src/actions/peg/index.ts, ui/core/src/api/EthbridgeService/EthbridgeService.ts, ui/core/src/api/EthbridgeService/parseTxFailure.ts, ui/core/src/api/SifService/SifService.ts, ui/core/src/hooks/removeLiquidityCalculator.test.ts, ui/core/src/hooks/removeLiquidityCalculator.ts
https://app.asana.com/0/1196233999049111/1199682492661683
=> Fix peg unpeg

ui/app/src/router/index.ts
fixes router issue where gtag not loaded
=> router/index: check if gtag

deploy/helm/sifnode/values.yaml
Change the voting period to three hours.
=> [ChainOps] Voting period.

smart-contracts/scripts/setup_eRowan.js
=> [ChainOps] eRowan tweaks.

deploy/helm/sifnode/templates/deployment.yaml, deploy/helm/sifnode/values.yaml, deploy/rake/cluster.rake
=> [ChainOps] Mint/bond args.

.github/workflows/release.yml
Comment out swagger/prism/sifcrg.
=> [ChainOps] Release fixes.

.github/workflows/feature.yml, deploy/helm/ebrelayer/values.yaml, deploy/helm/sifnode/values.yaml, deploy/terraform/providers/aws/variables.tf
Scale out the clusters, to accommodate the updated peggy memory requirements.
=> [ChainOps] Peggy memory updates.

.github/workflows/feature.yml, .github/workflows/release.yml, deploy/helm/ebrelayer/values.yaml, deploy/terraform/providers/aws/variables.tf, ui/app/src/components/currencyPairPanel/Index.vue, ui/app/src/components/currencyfield/CurrencyField.vue, ui/app/src/components/shared/AssetList.vue, ui/app/src/views/CreatePoolPage.vue, ui/app/src/views/PegAssetPage.vue, ui/app/src/views/PegListingPage.vue, ui/app/src/views/SwapPage.vue, ui/core/src/api/SifService/parseTxFailure.ts, ui/core/src/entities/Errors.ts
Recent UI and ChainOps updates.
=> Recent ChainOps and UI Updates.

ui/app/src/components/shared/ConfirmationModal.vue, ui/app/src/components/shared/ConfirmationModalSigning.vue, ui/app/src/types.ts, ui/app/src/views/PegAssetPage.vue, ui/core/src/actions/peg/index.ts, ui/core/src/api/EthbridgeService/EthbridgeService.test.ts, ui/core/src/api/EthbridgeService/EthbridgeService.ts
Minimal approach to approve modal.
=> [ui] feature/min-approve

ui/core/src/assets.ethereum.mainnet.json, ui/core/src/assets.sifchain.mainnet.json
Remove TRB, MKR, fix GRT address. This is supposed to be final cut.
=> [ui] Whitelist: {ethereum,sifchain}.mainnet: rm TRB, MKR, fix GRT address

.github/workflows/feature.yml, .github/workflows/release.yml, cmd/ebrelayer/txs/relayToEthereum.go, deploy/helm/ebrelayer/values.yaml, deploy/terraform/providers/aws/variables.tf, test/integration/src/py/test_random_currency_roundtrip.py, test/integration/start-integration-env.sh, ui/app/src/components/currencyPairPanel/Index.vue, ui/app/src/components/currencyfield/CurrencyField.vue, ui/app/src/components/shared/AssetList.vue, ui/app/src/components/shared/ConfirmationModal.vue, ui/app/src/components/shared/ConfirmationModalSigning.vue, ui/app/src/types.ts, ui/app/src/views/CreatePoolPage.vue, ui/app/src/views/PegAssetPage.vue, ui/app/src/views/PegListingPage.vue, ui/app/src/views/SwapPage.vue, ui/core/src/actions/peg/index.ts, ui/core/src/api/EthbridgeService/EthbridgeService.test.ts, ui/core/src/api/EthbridgeService/EthbridgeService.ts, ui/core/src/api/SifService/parseTxFailure.ts, ui/core/src/assets.ethereum.mainnet.json, ui/core/src/assets.sifchain.mainnet.json, ui/core/src/entities/Errors.ts
https://github.com/Sifchain/sifnode/issues/723
=> [Peggy] Sifchain -> Ethereum: Manual Nonce Management

ui/core/src/config.mainnet.json, ui/core/src/config.sandpit.json
Changes gas price per @Jedi2002 spec.
=> [ui] core/config: keplr gasPriceStep

app/app.go
Upgrade handler for the latest release.
=> [ChainOps] Upgrade 

ui/core/src/assets.ethereum.mainnet.json, ui/core/src/assets.sifchain.mainnet.json
Removes Golden Ratio Token. Is not on the Final List.
=> [ui] core/{eth,sif}.mainnet.json: remove golden ration token

ui/app/src/components/shared/DetailsPanelPool.vue, ui/core/src/utils/parseConfig.test.ts, ui/core/src/utils/parseConfig.ts
- Fix issue where values on pool confirmation dialog were flipped
- Fix issue where Keplr config received ALL currencies. Now only receives Sifchain ones
=> [ui] Smoke Test Bug Fixes

deploy/helm/logstash/.helmignore, deploy/helm/logstash/Chart.yaml, deploy/helm/logstash/templates/NOTES.txt, deploy/helm/logstash/templates/_helpers.tpl, deploy/helm/logstash/templates/configmap-config.yaml, deploy/helm/logstash/templates/configmap-pipeline.yaml, deploy/helm/logstash/templates/daemonset.yaml, deploy/helm/logstash/templates/ingress.yaml, deploy/helm/logstash/templates/poddisruptionbudget.yaml, deploy/helm/logstash/templates/podsecuritypolicy.yaml, deploy/helm/logstash/templates/role.yaml, deploy/helm/logstash/templates/rolebinding.yaml, deploy/helm/logstash/templates/secret.yaml, deploy/helm/logstash/templates/service-headless.yaml, deploy/helm/logstash/templates/service.yaml, deploy/helm/logstash/templates/serviceaccount.yaml, deploy/helm/logstash/templates/statefulset.yaml, deploy/helm/logstash/values.yaml, deploy/rake/cluster.rake
Integration of Halborn's logstash work.
=> [ChainOps] Monitoring.

ui/core/src/api/ClpService/ClpService.ts, ui/core/src/api/utils/SifClient/toPool.ts
So this should guard against a weird token in a pool causing errors in frontend.
=> [ui] (Not for go live) Silently guard against pools with weird tokens

ui/app/src/views/RewardsPage.vue
=> [ui] app/RewardsPage: copy changes

deploy/docker/mainnet/docker-compose.yml, deploy/docker/mainnet/entrypoint.sh, deploy/rake/genesis.rake, docs/chainOps/standalone/README.md, docs/chainOps/standalone/tutorials/betanet.md, docs/chainOps/standalone/tutorials/testnet.md
Better/cleaner way for the community to run a local betanet node.
=> [ChainOps] Docker for the community.

app/app.go
=> [ChainOps] Latest release.

ui/core/src/actions/peg/index.ts, ui/core/src/api/EthbridgeService/EthbridgeService.test.ts
Per @ElliotFriedman :
```
The fee for unpegging ethereum native assets will be 0.05856 eth
The fee for pegging rowan to erowan will be 0.05408
```
This PR should reflect those changes.
=> [ui] core/actions/peg: change peg (rowan -> erowan), unpeg fees

ui/core/src/api/ClpService/ClpService.test.ts, ui/core/src/api/ClpService/ClpService.ts, ui/core/src/api/EthbridgeService/EthbridgeService.test.ts, ui/core/src/api/EthbridgeService/EthbridgeService.ts, ui/core/src/api/SifService/SifService.test.ts, ui/core/src/api/SifService/SifService.ts, ui/core/src/api/utils/SifClient/SifClient.ts, ui/core/src/api/utils/SifClient/SifUnsignedClient.ts, ui/core/src/api/utils/SifClient/TendermintSocketPoll.test.ts, ui/core/src/api/utils/SifClient/TendermintSocketPoll.ts, ui/core/src/test/utils/services.ts, ui/core/src/utils/parseConfig.ts
NOTE: merging in to the polling branch
=> [ui] Poll vs ws fixes

ui/core/src/assets.ethereum.mainnet.json, ui/core/src/assets.sifchain.mainnet.json
From Asana:
> Update UI config to allow the following tokens: Cocos https://etherscan.io/token/0xc4c7ea4fab34bd9fb9a5e1b1a98df76e26e6407c
keep: https://etherscan.io/token/0x85eee30c52b0b379b046fb0f85f4f3dc3009afec
ogn: https://etherscan.io/token/0x8207c1ffc5b6804f6024322ccf34f29c3541ae26
=> [ui] core/{ethereum,sifchain}.mainnet: cocos, keep, origin

cmd/sifgen/main.go, deploy/helm/sifnode/templates/deployment.yaml, deploy/helm/sifnode/values.yaml, deploy/rake/cluster.rake, tools/sifgen/common/types/genesis.go, tools/sifgen/genesis/genesis.go, tools/sifgen/node/node.go
Includes:
* Updated rake task to set a URL the points to a list of Pools/LPs to setup at genesis.
* Updated Helm chart for sifnode.
* Updated sifgen logic to download, marshal and inject the list of Pools/LPs into the genesis file.
=> [ChainOps] Setup Pools/LPs at genesis.

app/app.go
Includes:
* Minor tweak to store the state export in `$HOME/.sifnoded` instead of `/`.
=> [ChainOps] State export

ui/app/src/components/poolStats/PoolStatsListItem.vue
Fixes APY bug where percentage not represented correctly.
=> [ui] app/poolstatslistitem: pool apy * 100

deploy/terraform/providers/aws/volumes.tf
Includes:
* Use the cluster name in the role and policy name.
=> [ChainOps] Volume snapshot role/policy tweaks

test/integration/src/py/test_ebrelayer_restart.py, test/integration/src/py/test_utilities.py
Adds tests for sifchain transactions happening while the relayers aren't running.
=> Add tests for ebrelayer restart (merge to feature/cosmos-checkpoint, not develop)

ui/core/src/assets.ethereum.mainnet.json, ui/core/src/assets.sifchain.mainnet.json
Elliot Friedman @michael Pierce @rudi Would appreciate if you guys could get a PR together to support these new tokens in our UI:
https://etherscan.io/token/0xd82bb924a1707950903e2c0a619824024e254cd1
https://etherscan.io/token/0x3e9bc21c9b189c09df3ef1b824798658d5011937
https://etherscan.io/token/0x525794473f7ab5715c81d06d10f52d11cc052804
https://etherscan.io/token/0xc4de189abf94c57f396bd4c52ab13b954febefd8
https://etherscan.io/token/0x8ab7404063ec4dbcfd4598215992dc3f8ec853d7
https://etherscan.io/token/0xaf9f549774ecedbd0966c52f250acc548d3f36e5
https://etherscan.io/token/0xf1f955016ecbcd7321c7266bccfb96c68ea5e49b
I should have the backend part done tomorrow. Let’s coordinate so we can get this done before EOD friday.
@ivan Verchenko I looked through all of the tokens and all of them are 18 …
=> core/assets: daofi, lina, tshp, b20, akro, rfuel, rly

app/app.go
Includes:
* Upgrade handler for the upcoming upgrade.
=> [ChainOps] New release.

deploy/docker/testnet/docker-compose.yml, docs/chainOps/k8s/tutorials/testnet.md, docs/chainOps/standalone/tutorials/testnet.md
Includes:
* Updated documentation for connecting to the new testnet, TestNet.
* Updated docker compose with the new testnet peers/RPC endpoint.
=> [ChainOps] TestNet documentation.

ui/core/src/assets.ethereum.mainnet.json, ui/core/src/assets.sifchain.mainnet.json
>Elliot Friedman  ... I would appreciate if you could help add the following tokens to our UI in betanet:
CONV https://etherscan.io/token/0xc834fa996fa3bec7aad3693af486ae53d8aa8b50,
RNDR https://etherscan.io/token/0x6de037ef9ad2725eb40118bb1702ebb27e4aeb24,
PAID https://etherscan.io/token/0x1614f18fc94f47967a3fbe5ffcd46d4e7da3d787
TIDAL https://etherscan.io/address/0x29cbd0510eec0327992cd6006e63f9fa8e7f33b7
=> [ui] ui/core: whitelist: conv, rndr, paid, tidal

ui/app/src/components/shared/utils.ts, ui/chains/cosmos/run.sh, ui/chains/peggy/run.sh, ui/core/src/config.localnet.json
This allows us to connect local config in local development environment. It also gets us to parity with the other config pattern.
=> [ui] ui/chains: sifchain -> sifchain-local

test/integration/sifchain_start_daemon.sh, test/integration/src/py/integration_env_credentials.py, test/integration/src/py/test_peggy_fees.py, test/integration/src/py/test_utilities.py
Tests for https://github.com/Sifchain/sifnode/pull/959
=> Tests for ceth account fees

ui/core/src/config.devnet.json, ui/core/src/config.testnet.json
Includes:
* Latest Bridge Bank Contract addresses as per the recent contract deployment.
=> [ui] Updated contract addresses.

app/app.go
Includes:
* Enabled the param-change governance subcommand.
=> [ChainOps] Governance update

.github/workflows/create-governance-request.yml, deploy/rake/cluster.rake
Changed pipeline logic to add second vote from different region
=> Added Second Validator to voting

app/app.go
Add evidence module to handle double signing
=> Add evidence module

app/app.go, app/setupHandlers.go
Includes:
* Missing governance routes to allow for the changing of parameters.
=> [ChainOps] Param changes.

ui/app/src/components/currencyfield/CurrencyField.vue
=> Remove select all on click

ui/app/src/components/tokenSelector/SelectTokenDialogSif.vue
Fix for: https://github.com/Sifchain/issues/issues/23
=> Remove balance restriction

cmd/ebrelayer/txs/relayToEthereum.go
Retry tx submission and getting receipt 30 times before giving up.
=> Add Retry Logic to Relayers

ui/app/src/views/RewardsPage.vue
Fixes minor typo / spelling error on the rewards tab in the sif dex.
=> Fix spelling on rewards tab.

docs/chainOps/k8s/tutorials/betanet.md, docs/chainOps/k8s/tutorials/testnet.md, docs/chainOps/standalone/tutorials/betanet.md, docs/chainOps/standalone/tutorials/testnet.md
Includes:
* Updates based on a recent PR submitted by one of the community members.
=> [ChainOps] Doc tweaks based on a recent PR.

docs/chainOps/standalone/tutorials/betanet.md, docs/chainOps/standalone/tutorials/testnet.md
Includes:
* minor updates as submitted by the community.
=> [ChainOps] Standalone validator documentation updates.

ui/app/src/views/PegListingPage.vue, ui/app/src/views/utils/sortAssetAmount.ts, ui/core/src/actions/peg/subscribeToUnconfirmedPegTxs.ts, ui/e2e/index.test.js
Closes: https://github.com/Sifchain/issues/issues/377
Adds a test to ensure against regressions
=> Pending peg rowan not showing

app/setupHandlers.go
Includes:
* Upgrade handler for 0.9.0-rc.1.
=> [ChainOps] Upgrade handler.

deploy/helm/cryptoeconomics/template.values.yaml, deploy/helm/cryptoeconomics/templates/deployment.yaml, deploy/rake/cluster.rake
added vault variables for cryptoeconomics template
logserach by contianer
=> [ChainOps] Automation changes

deploy/rake/cluster.rake
added create release by branch rake task
=> added create release by branch rake task

ui/app/src/views/RewardsPage.vue
Looks like there was a bad merge with the Rewards page which fails tests and somehow managed to get into develop? This has been breaking our deployments Eg. https://github.com/Sifchain/sifnode/runs/2585655752
=> [ui] Remove bad merge

ui/core/package.json, ui/package.json, ui/yarn.lock
* Remove mock-socket which we don't use and upgrade url-parse although not bundled in production code
=> [ui/dep] Upgrade url-parse

ui/core/src/entities/Amount.test.ts, ui/core/src/entities/Amount.ts, ui/core/src/utils/format.test.ts, ui/core/src/utils/format.ts, ui/core/src/utils/parseDynamicMantissa.test.ts
* Adds dynamic mantissa to format
* Adds sanity checks for Amount incase we accidentally throw typesafety away because of vue templates or forget to validate input structure in runtime (which we should probably do)
=> [ui] Add dynamic mantissa

ui/package.json, ui/yarn.lock
Upgrade lodash because of dependabot alert
=> [ui/dep] Upgrade lodash

deploy/rake/cluster.rake
fix for crypto pipeline. re-added helm_deploy it was stripped somehow.
=> fix for crypto pipeline

ui/app/src/components/shared/SifButton.vue, ui/app/src/views/SinglePool.vue
- also added a new state for sifbutton.
=> [ui] fixed blockexplorer button on pool page

cmd/ebrelayer/main.go, cmd/ebrelayer/relayer/cosmos.go, cmd/ebrelayer/relayer/cosmos_test.go, cmd/ebrelayer/replay.go, test/integration/execute_integration_tests_against_test_chain.sh, test/integration/sifchain_start_ebrelayer.sh, test/integration/src/py/test_ebrelayer_restart.py
Fixed issues with ebrelayer tests caused by 42 timing changes and fixed issues from a merge of the ebrelayer retry work
=> Fixed issues with ebrelayer tests caused by 42 timing changes and fixed issues from a merge of the ebrelayer retry work

ui/app/src/components/shared/RewardContainer/RewardContainer.vue, ui/app/src/components/shared/utils.ts, ui/app/src/views/RewardsPage.vue
Adds validator subsidy data to the Rewards Page. Also DRYs it out into `RewardContainer`
=> [hotfeature][ui][rewards] Validator Subsidy

deploy/rake/cluster.rake, deploy/rake/openapi.rake
Moved cluster:openapi:deploy,prism into openapi.rake openapi:openapi:deploy,prism
=> Standardizing Rake Tasks

test/integration/src/py/hackerfile.json, test/integration/src/py/test_dispensation_vulnerability.py
This is the last commit on develop that merges cleanly, might as well pull it in.  The next commit on develop (38a836f368ab48a3f480e033a5b740b5f08fa297) has conflicts.
=> Merge develop into 42 upgrade work

deploy/helm/block-explorer/templates/configmap.yaml
Fixes https://github.com/Sifchain/big-dipper/issues/24
=> Add networks from sifchain mainnet

test/integration/src/py/test_new_currency_transfers.py
The tests were written when I didn't understand the restrictions on cosmos denoms.
=> Remove obsolete tests for 42

deploy/rake/sifnode.rake
missing kubeconfig parameter in a couple of rake tasks
=> Chain ops/rake task fixes

test/integration/sifchain_start_ebrelayer.sh
This reverts commit 67e81c06f86682f0471d16b842db8266db2bf295.
=> Revert a test change

docs/general/CosmosSDK v.42 upgrade.md
Putting this in our repo, for reference.
=> Create CosmosSDK v.42 upgrade.md

cmd/ebrelayer/Dockerfile
Updated ebrelayer docker file to include sifnoded.
=> Updated ebrelayer docker file to include sifnoded.

smart-contracts/scripts/test/sifchainUtilities.js, test/integration/setup_sifchain.sh, test/integration/src/py/conftest.py
This should allow running tests locally now, and the same fix is working on develop (PR for that is https://github.com/Sifchain/sifnode/pull/1718)
=> Merge test fix to ibc

smart-contracts/LimitUpdating.md, smart-contracts/scripts/bulk_set_whitelist.ts, smart-contracts/src/hardhatFunctions.ts
Note: found what seems to be a (non-critical) bug in our smart contracts.
The operator can add a token to the whitelist even if the token is already there. That is not expected behavior.
=> script to bulk update the whitelist

cmd/ebrelayer/relayer/cosmos.go, docs/relayer/start-relayer.md
when implement the signature aggregation, forget to implement it. The pr generate the siganture against the prophecy from sifchain for lock/burn message.
=> signature added.

smart-contracts/LimitUpdating.md, smart-contracts/hardhat.config.ts, smart-contracts/scripts/bulk_set_whitelist.ts
- Explicitly sets the gas price for the bulk_set_whitelist;
- Changes the way we set .env variables (works well for the bulk_set_whitelist script)
=> Develop whitelist gas prices

docs/chainOps/standalone/tutorials/testnet.md
Includes:
* Minor tweak to correctly set the container ID when running a standalone version.
=> [ChainOps] Doc updates.

docs/chainOps/standalone/tutorials/betanet.md, docs/chainOps/standalone/tutorials/testnet.md
Includes:
* Removed the duplicate mnemonic step.
=> [ChainOps] Doc fixes.

cmd/ebrelayer/relayer/cosmosReplay.go
Code cleanup. 
Note: New number comes to 518400, is that fine?
=> Update const declaration to be more descriptive

.github/ISSUE_TEMPLATE/ibc_add_eth_token.md, .github/ISSUE_TEMPLATE/ibc_token_add.md
=> Issue templates for token registry requests

smart-contracts/scripts/bulk_set_whitelist.ts
=> fix: hardhat functions

smart-contracts/data/sifnode_mainnet_update_01_Oct_2021.json, smart-contracts/data/whitelist_mainnet_update_01_Oct_2021.json
Has the output files of Oct 1st whitelist update
=> whitelist output files

.github/workflows/release.yml
Includes:
* Set the version of golang that the release must be compiled with.
=> [ChainOps] Release tweaks

cmd/ebrelayer/txs/relayToEthereum.go
In this PR:
Add error logging from ethereum client response when tx failed
=> Add error logging when ethereumclient returns error

smart-contracts/data/sifnode_mainnet_update_06_Nov_2021.json
Includes:
* Latest token whitelisting results for:
```
0x99d8a9c45b2eca8864373a26d1459e3dff1e17f3
0x9040e237c3bf18347bb00957dc22167d0f2b999d
0x6524b87960c2d573ae514fd4181777e7842435d4
0x4691937a7508860f876c9c0a2a617e7d9e945d4b
0xe53ec727dbdeb9e2d5456c3be40cff031ab40a55
0x3506424f91fd33084466f402d5d97f05f8e3b4af
0x888888848b652b3e3a0f34c96e00eec0f3a23f72
```
=> [ChainOps] Whitelist update.

.github/workflows/release.yml
=> [ChainOps] Hotfix for releases.

cmd/ebrelayer/Dockerfile, cmd/sifnoded/Dockerfile, docker/localnet/sifnode/Dockerfile, docker/localnet/ts-relayer/Dockerfile
Includes:
* Update docker builds to golang 1.17.
=> [ChainOps] Docker

.github/workflows/go.yml
=> Add global code coverage

cmd/ebrelayer/main.go, cmd/ebrelayer/relayer/ethereum.go, cmd/ebrelayer/replay.go, smart-contracts/src/devenv/ebrelayer.ts
The pr resolve #2082, get the network id from command line, not depend on the id what chain report.
=> get the network id from cli

smart-contracts/src/tsyringe/devenvUtilities.ts, smart-contracts/src/tsyringe/hardhatSupport.ts
Removing unused param. Is this ok?
=> Update remove unneeded function param

smart-contracts/data/sifnode_mainnet_update_24_Nov_2021.json, smart-contracts/data/whitelist_mainnet_update_24_Nov_2021.json
=> [ChainOps] Whitelist updates.

app/app.go, app/setup_handlers.go
Upgrade for devnet and testnet from rc.3
=> 0.10.0-rc.4

smart-contracts/src/tsyringe/contracts.ts, smart-contracts/test/devenv/test_lockburn_erc20.ts
=> add new case peggy erc20 token

scripts/ibc/tokenregistration/sifchain-testnet-1/cbat.json, scripts/ibc/tokenregistration/sifchain-testnet-1/ceth.json, scripts/ibc/tokenregistration/sifchain-testnet-1/clink.json, scripts/ibc/tokenregistration/sifchain-testnet-1/cusdt.json, scripts/ibc/tokenregistration/sifchain-testnet-1/cwbtc.json, scripts/ibc/tokenregistration/sifchain-testnet-1/czrx.json
closes #2390 
The following tokens were added to the testnet whitelist
=> new ERC 20 token entries

docs/tutorials/clp tutorial.md
missing ` --keyring-backend=test` to get `sif` account addr.
=> Update clp tutorial.md

.github/workflows/peggy-docs.yml
Includes:
* Peggy 2 documentation pipeline.
=> [ChainOps] Peggy 2

docs/tutorials/margin tutoral.md
a tutorial attempt for margin @AustinoBombino @timlind
=> Create margin tutorial.md

cmd/sifnoded/Dockerfile
Includes:
* Minor fix to specify the exact version of `cosmovisor`.
=> [ChainOps] Cosmovisor

smart-contracts/Makefile
In this PR:
- Add hardhat artifact cleaning in makefile
- Add said invocation to be part of `make clean`
=> Add hardhat clean artifact in makefile

.github/workflows/gitleaks.yml, .github/workflows/go.yml, .github/workflows/localnet.yml, Makefile, test/integration/setup-linux-environment-root.sh
We should at least have this stuff running and passing if possible in peggy2 active branch.  Running on push,pull_request just ends up running twice often and isn't needed.  I have fixed at least unit tests so they run correctly, but integration and localnet tests are still broken.
=> Fix GitHub action go.yml tests

cmd/ebrelayer/relayer/cosmos.go
just remove a todo and update the comments for exceptional case.
=> Remove a TODO in relayer

x/clp/types/msgs.go
This is a hot fix to master for PR #2667
=> Fix unbond amino/ledger support

cmd/ebrelayer/main.go, cmd/ebrelayer/relayer/cosmos.go, cmd/ebrelayer/relayer/prophecyHandler.go
=> Use command-line log_level to configure zap logger

test/integration/framework/README.md, test/integration/framework/siftool, test/integration/framework/src/siftool/command.py, test/integration/framework/src/siftool/common.py, test/integration/framework/src/siftool/cosmos.py, test/integration/framework/src/siftool/eth.py, test/integration/framework/src/siftool/geth.py, test/integration/framework/src/siftool/hardhat.py, test/integration/framework/src/siftool/inflate_tokens.py, test/integration/framework/src/siftool/localnet.py, test/integration/framework/src/siftool/main.py, test/integration/framework/src/siftool/project.py, test/integration/framework/src/siftool/run_env.py, test/integration/framework/src/siftool/sifchain.py, test/integration/framework/src/siftool/test_utils.py, test/integration/framework/test/conftest.py, test/integration/framework/test/test_geth.py, test/load/conftest.py, test/load/load_testing.py, test/load/siftool_path.py, test/load/test_liquidity_pools.py
These are the changes of siftool from `future/peggy2` branch.
This is mainly upon @sheokapr's request so that he can work on load testing for CLP refactoring on `feature/peggy-decimals` branch. I recommend to first merge these changes to `develop` and then merge `develop` to `feature/peggy-decimals`, but it can also be done the other way around.
I've already added some functions for working with CLP pools to siftool in `test/integration/framework/src/siftool/sifchain.py`. See functions `tx_clp_add_liquidity()`, `tx_clp_unbond_liquidity()` etc. Some of the functions are still just placeholders and need to be implemented, but the existing functions should be enough to give you an idea how to do it.
I've also added a short example how to implement a CLP test in …
=> Cumulative update of siftool from future/peggy2 branch

.github/workflows/release.yml
Includes:
* Fix for triggering a remote workflow.
=> Workflow trigger.

app/app.go, x/bank/keeper/grpc_query.go, x/bank/module.go
This PR limits the pagination for the "all balances" query on the bank module.
=> limit pagination on all balances query

x/oracle/genesis_test.go
The comment for old peggy version 0.39.
=> remove todo for issue 2825

x/clp/types/msgs.go
In this PR:
Improve readability 
Resolves https://app.zenhub.com/workspaces/current-sprint---engineering-615a2e9fe2abd5001befc7f9/issues/sifchain/sifnode/2903
TODO:
Should also create PR for develop branch
=> Improve newMsgSwap func readability

cmd/ebrelayer/relayer/cosmos.go
=> Panic on improper BurnLockEventToCosmos Message

Makefile
=> Create test-bin makefile target to separate go tests

x/margin/keeper/keeper.go
Typo in interest rate change condition.
=> Fix Interest Rate Computation

x/tokenregistry/types/codec.go
In this PR:
Register missing new messages
=> Certik Audit remediation - Codec registration

x/margin/keeper/abci.go, x/margin/keeper/keeper.go, x/margin/keeper/msg_server.go, x/margin/types/expected_keepers.go
Handle margin fund routing for outstanding interest on mtp closures.
=> Close Interest Margin Fund Rounting

smart-contracts/.prettierrc, smart-contracts/contracts/Oracle.sol, smart-contracts/test/testCosmosBridge.ts
In this PR:
Add privileged function to update CosmosBridge.sol::consensusThreshold to be in sync with value stored in sifnoded
=> Smart contract function to update consensusThreshold

smart-contracts/test/testBridgeBank.ts
In this PR:
- Add missing test to verify bridgebank burn checks blocklist
- Formatting
=> Smart contract test for OFAC blocklist

Makefile, x/oracle/types/crossChainFeeConfig.go
Also fixed a minor lint warning.
=> lint depends on generating the protobuf files, fixed the makefile

x/clp/keeper/invariants.go, x/clp/keeper/msg_server.go, x/margin/keeper/msg_server.go, x/margin/types/expected_keepers.go
Previous version of invariant checks caused gas fee to increase significantly when running at msg server level.
=> fix: 🐛 optimize invariant checks

x/clp/keeper/invariants.go, x/clp/keeper/msg_server.go, x/margin/keeper/keeper.go, x/margin/keeper/keeper_test.go, x/margin/keeper/msg_server.go, x/margin/keeper/msg_server_test.go, x/margin/types/expected_keepers.go
Update Peggy 2 to current trunk.
=> Peggy2 update merge

docs/peggy/docs/README.md
Added instructions to run peggy locally via siftool
=> Add docs on how to run locally

cmd/ebrelayer/relayer/ethereum.go
In this PR:
Remove replay function, no longer supported in peggy2
=> Remove deprecated peggy1 function

x/clp/keeper/calculations.go, x/clp/keeper/msg_server.go, x/clp/keeper/msg_server_test.go
Specs: https://www.notion.so/sifchain/Dex-Liquidity-Protection-with-Dynamic-Swap-Fee-07f5e36b33c14b0f8a7d873de6a7b047
=> fix: 🐛 DLP discounted sent amount
