Sifchain/sifnode

scripts/setup-e2e.sh
Some tester get all kinds of error when run init scripts to generate bin files. comment the step out and use the bin file already checked in. Will add it back, reference issue 1.
=> remove the generate bin step since all solidity bin file checked in

build/helm/sifnode/templates/storageclass.yaml, build/terraform/providers/aws/main.tf, build/terraform/providers/aws/variables.tf
- Previously I replaced EBS with EFS type of storage but we still need EBS for the single pods to save data on Persistent Storage.
- I also moved the StorageClass-es deployment to be part of the Terraform setup.
=> [ChainOps] EBS CSI plugin and StorageClass in Terraform

deploy/rake/cluster.rake
Added an additional `:cluster` argument. This is necessary when deploying across different clusters when they all participate on the same Chain/Network.
This also allows us to slowly decouple `:chainnet` away from the cluster name itself. Currently just updated for the relayer.
=> [ChainOps] Set the correct chain ID for the relayer.

test/integration/test_chain_rollback.py
Rounding issues in the javascript testing libraries mean that it's problematic to just use 1 wei.
=> [Peggy] Integration tests need to use a slightly larger amount to work around javascript issues

deploy/terraform/providers/aws/variables.tf
Increase the default k8s compute instance from t2.medium to t2.xlarge.
=> [ChainOps] Terraform tweaks.

ui/core/src/actions/clp/index.ts, ui/core/src/api/ClpService/ClpService.ts, ui/core/src/api/SifService/SifService.ts
There was a bug in the peg UI after the refactor to share a socket connection. Forgot to run the pool sync on initialize. 
This does it properly in app/clp using event hooks exposed by SifService which should manage the main relationship to sifchain.
Lesson: we should prioritise cypress testing as soon as we can to avoid this sort of stuff.
=> [Frontend] Fix swap not working because pools not loading

ui/core/src/actions/clp/index.ts
This stops this thing for liquidity pools:
=> [Frontend] Only send notification once pools object changes

cmd/sifgen/main.go, tools/sifgen/common/types/genesis.go
Was using the wrong field name for the CLP admin addresses.
=> [ChainOps] Sifgen hotfix.

cmd/ebrelayer/relayer/ethereum.go
If relayer continuously send the multiple transactions to cosmos, we get a wrong sequence number error. add three seconds sleep to make sure last transaction processed before sending next one.
=> fix wrong sequence number.

cmd/ebrelayer/relayer/ethereum.go
ebrelayer need longer time for cosmos process the transaction and sync up state before sending next transaction.
=> update transaction interval to 10 seconds.

ui/app/src/views/CreatePoolPage.vue, ui/app/src/views/SwapPage.vue, ui/core/src/entities/AssetAmount.ts, ui/core/src/entities/fraction/Fraction.ts, ui/core/src/hooks/addLiquidityCalculator.test.ts, ui/core/src/hooks/addLiquidityCalculator.ts, ui/core/src/hooks/swapCalculator.test.ts, ui/core/src/hooks/swapCalculator.ts
When Max button was built there appeared to be some issues with sending transactions that maxed out accounts and we needed to supply amounts just shy of the max. To compensate the max button filled out balance close to the max amount but just shy of it as a temporary measure. It now appears that we can remove this as our product has stabilised. 
* Boundary tests
* Added new `lessThanOrEqual` and `greaterThanOrEqual` methods on `AssetAmount` and `Fraction`
=> [Frontend] Fix max button

ui/app/src/views/CreatePoolPage.vue, ui/core/src/hooks/addLiquidityCalculator.test.ts, ui/core/src/hooks/addLiquidityCalculator.ts
* Fix bug which was zeroing liquidity amount on add liquidity calculator.
* Refactored from/to field to tokenA/tokenB to make more sense
* Updated tests
=> Fix liquidity calulator without preexisting liquidity

ui/app/src/components/confirmationDialog/ConfirmationDialog.vue, ui/app/src/components/confirmationDialog/PoolConfirmationDialog.vue, ui/app/src/components/confirmationDialog/RemoveConfirmationDialog.vue
This avoid the double keplr popup that can also result in the `Request Rejected` error in notifications.
https://app.asana.com/0/1199521986937893/1199701491050017
=> [ui] Turn off inheriting attrs for component dialogs to avoid double event firing

ui/app/src/components/shared/AssetList.vue, ui/app/src/components/shared/utils.ts, ui/app/src/views/PegAssetPage.vue, ui/app/src/views/PegListingPage.vue
This applies particularly to display values. Fixes future issue where app would crash if decimals of asset on pegAssetPage < 18. This would apply to main net tokens like `USDT` which have 6 decimals. 
Also, applies `formatNumber` in AssetList (Peg)
=> [ui] bug/decimals

ui/app/src/views/CreatePoolPage.vue
Fixes issue where back button from `/pool/add-liquidity/<token>` went back to `/pool` instead of `/pool/<token>`
=> [ui] app/CreatePoolPage: fix back link logic

ui/app/src/components/shared/Tabs.vue, ui/app/src/views/PegListingPage.vue, ui/core/src/assets.ethereum.localnet.json
There was an issue with the tab component where it was not setup to manage defaults properly.
This adds a `defaultIndex` prop to manage the default selected Index.
This meant that the wrong token peg and unpeg links were being shown to the user which meant that peg and unpeg were not working when clicked through
There was also some bad config in the localconfig where sifchain assets were being listed in the ethereum asset config.
=> Fix issue with tabs showing the wrong peg/unpeg buttons. Remove bad config

ui/core/src/api/EthbridgeService/EthbridgeService.ts
Issue #789. 
Some users see huge gas fee when peg erowan (`burn`). This fix hard codes the gas estimate at `150000` (bumped to 150k per Eliot recommendation). Most transactions used between 40-55k gas (Reference: https://etherscan.io/address/0xb5f54ac4466f5ce7e0d8a5cb9fe7b8c0f35b7ba8). An alternate method to solve this issue is to invoke `burn(params).gasEstimate({fromAddress})`.
=> [ui] core/ethBridgeService: hard code gas limit for burn

ui/core/src/actions/clp/index.ts
Because we are not just blowing away an array anymore and have replaced with a hash remove liquidity was not updating the list of pools. We don't have the option of blowing away the object or that will cause flicker as new pools load so. We need to go through each individually and remove them.
=> [ui-hotfix] Remove liquidity pool from pool list

ui/app/public/index.html, ui/app/src/App.vue, ui/app/src/components/shared/Tooltip.vue
* Tool tip was clipping in an overflow hidden situation
* This puts it in it's own teleport target to be more scalable
=> [ui] Fix up tooltip

ui/core/src/api/EthbridgeService/EthbridgeService.ts
- Manually set `approve` `gasLimit` to `100000`
- Manually set `lock` `gasLimit` to `150000` (same as for `burn`)
=> [ui] core/EthBridgeService: manual lock and approve gas limits

ui/core/src/api/SifService/getKeplrProvider.ts
Hotfix candidate: Keplr changed their API without notifying us. Has breaking changes. Prevents users from connecting wallet, transacting.
=> [ui][hotfix candidate] core/getKeplrProvider: rm line that breaks bc keplr api changes

ui/core/src/api/SifService/getKeplrProvider.ts
Hotfix candidate: Keplr changed their API without notifying us. Has breaking changes. Prevents users from connecting wallet, transacting.
=> [ui][hotfix] core/getKeplrProvider: rm line that breaks bc keplr api changes

ui/docs/EventBusService.md
Before we forget, moved Rudi's https://github.com/Sifchain/sifnode/pull/892, PR comment to `/docs` folder.
=> [ui] ui/docs/EventBusService: Rudi's PR as a doc

deploy/helm/block-explorer/templates/configmap.yaml
Adds current whitelisted Sifchain tokens to the Block Explorer. Also, updates `coingeckoId` so the price should now show. 
Additional note: I foresee this as a trial run for further Block Explorer changes.
=> [ChainOps] Explorer Tokens

ui/core/src/assets.sifchain.mainnet.json
"c" prefix missing for Sifchain assets.
=> [ui] sifchain, missing "c" prefix, daofi, lina, tshp, b20, akro, rfuel, rly 

ui/core/src/assets.sifchain.mainnet.json
This adds "c" prefix to the new Sifchain assets (`daofi, lina, tshp, b20, akro, rfuel, rly`)
=> [ui] core/sifchain.mainnet: add "c" prefix

ui/core/src/config.devnet.json, ui/core/src/config.testnet.json
UI fix to rename `testnet` and `devnet` chains to `sifchain-testnet` and `sifchain-devnet` respectively. This will allow for Keplr to properly differentiate between environments so transactions are broadcast to the right endpoints.
=> [testnet-hotfix][ui] ui/core: testnet, devnet chainId (semi) fix

ui/core/src/api/SifService/SifService.ts
Every Sifchain transaction fails due to "out of gas" causing less than stellar UX. This bumps up gas to prevent this.
=> [ui] hotfix/bump sif gas

test/integration/setup-linux-environment-user.sh
Possible fix for our truffle issue.  We used to need sudo to install, and it's possible that we can't use sudo any more.
=> Truffle update requires no sudo for install

test/integration/setup-linux-environment-user.sh, test/integration/src/py/conftest.py, test/integration/src/py/test_peggy_fees.py
The previous version of this test could only be run once.  Change the test so it resets the state of the chain and the test can be repeated.
=> Improve rescue ceth tests

deploy/helm/block-explorer/templates/configmap.yaml
Includes:
* Fixes a bug where the configmap referenced the old config for the API URL.
=> [ChainOps] Explorer bugfix.

ui/app/src/components/shared/Icon.vue, ui/app/src/views/RewardsPage.vue
This better handles decimal values and includes a tooltip which displays current multiplier.
=> [ui] hotfix: ui/app/RewardsPage: Multiplier tooltip, decimals

ui/app/src/components/shared/SifButton.stories.ts, ui/app/src/components/shared/SifButton.vue, ui/app/src/views/PegAssetPage.vue, ui/app/src/views/PegListingPage.vue, ui/core/src/actions/ethWallet.test.ts, ui/core/src/actions/ethWallet.ts, ui/core/src/actions/peg/index.ts, ui/core/src/actions/utils/index.ts, ui/core/src/api/EthereumService/EthereumService.ts, ui/core/src/api/EthereumService/utils/ethereumUtils.ts, ui/core/src/api/IWalletService.ts, ui/core/src/api/SifService/SifService.ts, ui/core/src/store/wallet.ts, ui/core/src/test/utils/getMockWalletService.ts
This PR disables pegging when the user is not connected to a supported EVM network. 
After consultation with @j-kappa this adds a few interim (not fancily designed) usability guards for when connecting to an unsupported EVM network:
This probably can't happen because of the guards but if you succeed at executing the peg action on an unsupported network you get this:
=> [ui] Feature/prevent unpeg bsc

ui/app/src/components/shared/utils.ts
Closes: https://github.com/Sifchain/issues/issues/328
What was happening is that the algo wasn't taking in the asset decimals into account when calculating the pivot number.
=> Fix decimal places in listing

app/app.go, cmd/sifnoded/main.go
Includes:
* Minor update to correctly set the prefix as `sif`, not `cosmos` (default).
* Fixed the spelling mistake `.sifenoded` and replaced with `.sifnoded`.
=> [ChainOps] Set the address prefix.

deploy/rake/cluster.rake
On the rare condition multiple runs exist for a release when troubleshooting there are multiple jobs and so had to add a selection to only select the first entry returned from github jobs api so it doesn't take subsequent runs even if set job run has been deleted.
added exit 1  condition to rake task for waiting for release pipeline if max conditions met.
=> Governance Request Logic Changes and Hardening

deploy/rake/cluster.rake
kubectl was missing l for namespace creation
=> kubectl was missing l for namespace creation

ui/core/src/api/EthbridgeService/EthbridgeService.ts, ui/core/src/entities/AssetAmount.test.ts, ui/core/src/entities/AssetAmount.ts
Fixes issue where `tokenContract.methods.approve()` was not receiving token amount in baseUnits. Also updated `allowance()` logic to use baseUnits.
=> [testnet] ui/core/EthBridgeService: convert assetAmount into Base Units

ui/app/src/views/PegAssetPage.vue, ui/core/src/api/EthbridgeService/EthbridgeService.ts, ui/core/src/entities/AssetAmount.test.ts, ui/core/src/entities/AssetAmount.ts, ui/core/src/hooks/addLiquidityCalculator.ts, ui/e2e/ethereum.js, ui/e2e/index.test.js, ui/e2e/keplr.js, ui/e2e/metamask.js, ui/e2e/package.json, ui/test/tsconfig.json, ui/yarn.lock
Referenced by https://github.com/Sifchain/issues/issues/396
With reference to https://sifchain.slack.com/archives/G01BX71QY1F/p1619822131293500
Unfortunately [this fix](https://github.com/Sifchain/sifnode/pull/1222) solved the problem at the wrong level of abstraction missing the actual bug which was that the amount was not being converted to baseunits in the view code.
This fixes the bug in approval baseunit as well as adds an accompanying test. 
~I believe we will want to revert #1222 and merge this to the release from develop.~
This reverts #1222 and replaces it with a fix within the view.
This does not acknowledge the underlying architectural issue which is that approve should be called in the usecase not the view. 
---
Testing changes were done in order to make the test work.
To do …
=> [ui] Fix approval baseunits bug

deploy/helm/cryptoeconomics/values.yaml
Includes:
* Set a minimum of 8Gi and a max of 16Gi for the cryptoeconomics container.
=> [ChainOps] Cryptoeconomics container resource tweaks.

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
A simple dev container for VSCode which includes the following: 
Programming Languages:
- Go 1.16
- Node
System Libraries: 
- tmux
- netcat
Node Libraries:
- ganache-cli
When you open VSCode the project will automatically start a container with the tools required to run some of the basic tests, if you have the Remote Containers extension installed. It's a nice workflow :)
=> Add dev container for VSCode

Makefile
We can turn this on after we release protobuf files.
=> No need to check against breaking changes to protobuf files

cmd/sifnoded/cmd/add_genesis_validator_test.go
This tests the cmd interface for add-genesis-validator and the init genesis in oracle module, using a temporary home directory.
A regression test for previous bug.
=> Test add-genesis-validator cmd

.github/workflows/ui-stack.yml, ui/README.md
This is WIP and is forked from an active PR which is waiting to be merged -> https://github.com/Sifchain/sifnode/pull/1458 once that is merged this can follow quickly to maintain adequate test coverage. I will start by setting this to target the `ryardley/438-remove-ui-code` branch for greater readability but once that is merged this can target develop.
Get backend testing frontend code
So the idea here is that we need to avoid the situation where a breaking change gets merged to develop on sifnode then gets deployed without the frontend being ready to accept and manage the change. At worst this is going to require the backend teams and frontend teams to coordinate releases on the odd occasion that there are breaking changes from the backend.
=> Backend tests frontend

.github/workflows/ui-stack.yml
This means that every time we push to `feature/cosmos-0.42` a ui-stack image is created.
We should be able to then test the frontend against the `feature/cosmos-0.42` stable tag. Eg.
`yarn e2e --tag feature/cosmos-0.42`
=> Add cosmos branch to ui-stack build list

smart-contracts/contracts/BridgeBank/IbcToken.sol, smart-contracts/test/test_ibcToken.js
=> Replacing the ownable pattern with RBAC

test/integration/src/py/test_ebrelayer_replay.py
Any replays of ibc tokens or rowan need to go through the symbol translation code that was added for ibc.  This PR just modifies the replay test so it uses rowan instead of eth as the test currency.
=> Modify replay tests to use rowan so it goes through the symbol translation

smart-contracts/contracts/BridgeBank/BridgeBank.sol, smart-contracts/contracts/BridgeBank/CosmosWhiteList.sol, smart-contracts/test/test_bridgeBankLock.js
"Remove the whitelist being needed to lock tokens in the bridgebank.
Instead, add a check that whenever a token is locked, it is not in the cosmoswhitelist, and if it is, revert."
=> Remove the whitelist being needed to lock tokens in the bridgebank

smart-contracts/Whitelist_Update.md
=> Update whitelisting runbook

cmd/ebrelayer/relayer/cosmos.go
Includes:
* Minor tweak to remove the logging of `block.TxsResults`. In times like we're in now, with a substantial amount of transactions per block, it generates a significant amount of logging data that appears to have little to no value.
=> [ChainOps] Peggy Logging

.github/workflows/release.yml, Makefile
Includes:
* No longer prefix builds by the network (not necessary).
* Updated the release action to correctly set `ldflags`.
* Cleanup of the `sifnode` Makefile.
=> [ChainOps] Build updates

test/integration/setup_sifchain.sh, test/integration/sifchain_start_daemon.sh
Minor cleanup, these commands were not working anyway (they were failing silently).
I checked that removing them has no effect on any integration tests.
Already blessed by @banshee.
=> Remove invalid/broken commands for integration tests

smart-contracts/contracts/BridgeBank/BridgeBank.sol, smart-contracts/test/test_bridgeBankLock.js
- Removed the function `multiLock` from BridgeBank
- Changed all tests that used to call `multiLock` so that they now call `multiLockBurn`, maintaining everything else as was.
=> removing multiLock() in favor of multiLockBurn()

scripts/ibc/tokenregistration/sifchain-testnet-1/cbat.json, scripts/ibc/tokenregistration/sifchain-testnet-1/ceth.json, scripts/ibc/tokenregistration/sifchain-testnet-1/clink.json, scripts/ibc/tokenregistration/sifchain-testnet-1/cusdt.json, scripts/ibc/tokenregistration/sifchain-testnet-1/cwbtc.json, scripts/ibc/tokenregistration/sifchain-testnet-1/czrx.json
Fixes decimal precisions on testnet for 
Added IBCIMPORT permission for
=> Fixes decimal precisions or USDT and WBTC and adds IBCIMPORT to all ETH tokens

smart-contracts/src/devenv/sifnoded.ts, test/integration/framework/sifchain.py, x/tokenregistry/client/cli/tx.go
The register-all doesn't work in the future/peggy2 branch, it generates multiple TXs according to items number in the json file. we can see the wrong sequence issue for second tx and following. 
The PR remove the interface and update set registry, also update integration test.
=> remove register all

smart-contracts/contracts/BridgeBank/BridgeBank.sol, smart-contracts/scripts/watcher.ts, smart-contracts/src/contractSupport.ts, smart-contracts/src/devenv/ebrelayer.ts, smart-contracts/src/watcher/watcher.ts, smart-contracts/test/devenv/evm_lock_burn.ts, smart-contracts/test/devenv/sifnode_lock_burn.ts, smart-contracts/test/test_bridgeBankLock.js
Also avoid recalculating recipient.length on every pass through the loop
=> In multiLockBurn, update lockBurnNonce before we do any external calls.

cmd/sifgen/main.go, tools/sifgen/node/node.go
Includes:
* We'll now enable the API and gRPC by default. There was no need to not enable these services. We will still have control over making said services available to the outside world however (via helm).
=> [ChainOps] API/gRPC updates for sifgen

x/clp/keeper/pmtp.go
The existing calc isn't inclusive of the first block of a policy. Add one to the exponent to compensate.
=> PMTP - fix first block calc

cmd/sifnoded/cmd/add_genesis_validator_test.go, cmd/sifnoded/cmd/gentx.go
add_genesis_validator_test.go wasn't testing that the power was correct, just that the validator was added.  The power isn't correct.
Issue #2658
=> add_genesis_validator_test.go wasn't testing that the power was correct

test/integration/framework/siftool, test/integration/framework/src/siftool/common.py, test/integration/framework/src/siftool/cosmos.py, test/integration/framework/src/siftool/eth.py, test/integration/framework/src/siftool/inflate_tokens.py, test/integration/framework/src/siftool/sifchain.py, test/integration/framework/src/siftool/test_utils.py, test/integration/setup-linux-environment-user.sh, test/integration/src/peggy2/siftool_path.py, test/load/load_testing.py, test/load/siftool_path.py, test/load/test_many_denoms.py, test/localnet/utils/tests/__snapshots__/getChains.test.mjs.snap
This test creates up to 5000 ERC20 tokens and transfers them to a single sif account.
It checks that the wallet is usable (it can transfer funds to/from another sif wallet and do ethbridge burn).
It asserts that the fees are constant.
It measures the relative performance of a wallet with many denoms vs. wallet with one denom.
This PR is part of #2520.
=> Load test: many denoms sif wallet

x/clp/client/cli/tx.go
Unit argument was getting cast to uint64 which was causing overflow with large unit values
=> Fix unlock/cancel unlock cli

cmd/ebrelayer/txs/registry_test.go
there are lots of integration tests to verify registry contract. not very necessary to do it in unit test
=> remove todo for 2828

x/ethbridge/keeper/querier.go
Currently, all queries are provided from ethbridge module. It is not so necessary to move these queries to oracle module.
=> remove todo for issue 2823

x/margin/keeper/keeper.go
Update to mtp open accounting in pool balances per @Rubz2021 PR here: https://github.com/Sifchain/margin_trading_cadCAD/pull/159/files#
changes to s_swap_X_A
=> Fix: margin open pool accounting

x/margin/keeper/abci.go
abci.go was overwriting pool changes made by automatic force close. this was causing the close accounting issues that we were seeing. I moved the set pool to before the mtp close checks and things are working.
this issue was only present for the automated force close, not the normal close and force close transactions.
=> Fix Protocol Automatic Force Close

x/clp/client/cli/query.go
In this PR:
Resolves https://app.zenhub.com/workspaces/current-sprint---engineering-615a2e9fe2abd5001befc7f9/issues/sifchain/sifnode/2899
Fix is already in place in develop. Cherry-picked fix commit
=> Fix bug in GetCmdAssets

cmd/ebrelayer/main.go
We really only had two logging levels before; added more granularity.
=> Add more logging level support

cmd/ebrelayer/main.go, cmd/ebrelayer/relayer/ethereum.go, cmd/ebrelayer/txs/relayToCosmos.go
In load testing, the TPS from Ethereum to Sifnode just 1. add new argument maxMessagesInSifnodeTransaction in ebrelayer, then relayer can put more messages in a single transaction.
=> add new argument maxMessagesInSifnodeTransaction 

app/export.go, cmd/ebrelayer/internal/symbol_translator/symbol_translator.go, cmd/sifgen/main.go, scripts/ibc/channeldata/main.go, scripts/ibc/tokenregistration/main.go, tools/sifgen/genesis/genesis.go, tools/sifgen/network/network.go, tools/sifgen/node/node.go, tools/sifgen/sifgen.go, tools/sifgen/utils/cli.go, tools/sifgen/utils/cli_test.go, x/clp/client/cli/tx.go, x/clp/keeper/table_test.go, x/clp/scenarios_test.go, x/clp/test/test_common.go, x/dispensation/keeper/executors_test.go, x/dispensation/utils/parser.go, x/dispensation/utils/parser_test.go, x/ethbridge/client/cli/tx.go, x/tokenregistry/utils/parse_denom_list.go, x/tokenregistry/utils/parser_test.go
According to Halborn, the ioutil package was out of date, we could use both os and io to replace it.
=> remove ioutils

.github/workflows/integrationtest1.yml, .github/workflows/integrationtest2.yml
In this PR:
Temporarily disable log archiving.
Should update to archive the appropriate logs instead
Shaves 5-10 min on Integration test github actions
Currently not archiving the correct files anyway
=> Disable github action to store logs
